Repository canonical/chisel-releases, pull requests merged in 2025-10, with the labels that each got.

#688 feat(24.04): add locale binary
  slices/libc-bin.yaml
  tests/spread/integration/libc-bin/task.yaml
Labels: ready to merge

#689 feat(25.04): add locale binary
  slices/libc-bin.yaml
  tests/spread/integration/libc-bin/task.yaml
Labels: ready to merge

#670 feat(25.10): update new/missing files in apparmor for 25.10
  slices/apparmor.yaml
Labels: ready to merge

#661 fix(25.10): update gearman dependencies
  slices/gearman-job-server.yaml
  slices/gearman-tools.yaml
  slices/libboost-program-options1.88.0.yaml
Labels: ready to merge

#696 fix: pass chisel version to install_slices.py
  .github/scripts/install-slices/install_slices.py
  .github/workflows/install-slices.yaml
Labels: ready to merge

#647 feat(25.10): missing copyright + nitpicks
  slices/dpkg.yaml
  slices/libgdk-pixbuf-2.0-0.yaml
  slices/libpython3.13-stdlib.yaml
  slices/openssh-server.yaml
  slices/openssh-sftp-server.yaml
  slices/tar.yaml
  slices/vim-common.yaml
Labels: ready to merge

#690 feat(25.10): add locale binary
  slices/libc-bin.yaml
  tests/spread/integration/libc-bin/task.yaml
Labels: Priority, ready to merge

#702 feat(25.10): update sudo for 25.10
  slices/sudo.yaml
Labels: Priority, ready to merge

#713 feat(25.10): update procps for 25.10
  slices/procps.yaml
Labels: Priority

#685 fix(24.04): base-files_etc - add /etc/profile.d
  slices/base-files.yaml
Labels: ready to merge

#686 fix(25.04): base-files_etc - add /etc/profile.d
  slices/base-files.yaml
Labels: ready to merge
